apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-leqr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-leqr
    app.kubernetes.io/part-of: test-app-sntx
  name: test-component-leqr
  namespace: build-e2e-hacbs-xgyv
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: test-component-leqr
status:
  loadBalancer: {}
